# Generated by Django 6.0 on 2026-02-05 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
